from cihatbot.framework.events import Event


# Events generated by Ui or its submodules
class UiEvent(Event):
    pass


# Events generated by Trader or its submodules
class TraderEvent(Event):
    pass


# fires app.add_user
class AddUserEvent(UiEvent):
    name = "NEW_USER"
    data_fields = {"user"}


# fires app.config
class ConfigEvent(UiEvent):
    name = "CONFIG"


# fires user.add_trader
class AddTraderEvent(UiEvent):
    name = "ADD_TRADER"
    data_fields = {"trader"}


# fires user.add_ui
class AddUiEvent(UiEvent):
    name = "ADD_UI"
    data_fields = {"ui"}


# fires trader.add
class AddOrderEvent(UiEvent):
    name = "ADD"
    data_fields = {"order", "mode"}


# fires trader.cancel
class CancelOrderEvent(UiEvent):
    name = "CANCEL"
    data_fields = {"order_id"}


# fires trader.ticker
class TickerEvent(TraderEvent):
    name = "TICKER"


# fires trader.clock
class ClockEvent(TraderEvent):
    name = "TIMER"


# fires ui.submitted
class SubmittedEvent(TraderEvent):
    name = "SUBMITTED"
    data_fields = {"all", "single"}


# fires ui.filled
class FilledEvent(TraderEvent):
    name = "FILLED"
    data_fields = {"all", "single"}


# fires ui.rejected
class RejectedEvent(TraderEvent):
    name = "ERROR"
    data_fields = {"order", "message"}
